<?php
$lang = [
    // Header & Footer
    'app_title' => 'ResumeForge',
    'nav_create_resume' => 'Create Resume',
    'nav_preview_design' => 'Preview Design',
    'footer_copyright' => '&copy; ' . date('Y') . ' ResumeForge. All Rights Reserved.',

    // Index Page
    'form_main_title' => 'Auto Resume Creator',
    'form_main_subtitle' => 'Fill in the details below to generate your professional resume.',
    'template_selection' => 'Resume Template',
    'template_modern' => 'Modern Two-Column',
    'template_classic' => 'Classic Single-Column',
    'options' => 'Options',

    // Field Labels & Legends
    'personal_details' => 'Personal Details',
    'profile_photo' => 'Profile Photo',
    'full_name' => 'Full Name',
    'professional_tagline' => 'Professional Tagline',
    'email' => 'Email',
    'add_email' => 'Add another email',
    'phone' => 'Phone',
    'physical_address' => 'Physical Address',
    'github_profile' => 'GitHub Profile',
    'career_objective' => 'Career Objective',
    'professional_summary' => 'Professional Summary',
    'employment_history' => 'Work Experience',
    'job_type' => 'Job Type',
    'job_type_full_time' => 'Full-time',
    'job_type_part_time' => 'Part-time',
    'job_type_contract' => 'Contract',
    'job_type_internship' => 'Internship',
    'job_type_freelance' => 'Freelance',
    'job_grade' => 'Official Grade / Annotation (Optional)',
    'projects' => 'Projects',
    'education' => 'Tertiary Education (University / College)',
    'secondary_education' => 'Secondary Education (SPM / O-Level)',
    'school_name' => 'School Name',
    'graduation_year' => 'Graduation Year',
    'key_achievements_grades' => 'Key Achievements & Grades',
    'skills' => 'Technical & Professional Skills',
    'languages' => 'Languages',
    'language_name' => 'Language',
    'language_proficiency' => 'Proficiency / Test Score',
    'skill_name' => 'Skill Name',
    'proficiency_level' => 'Proficiency Level',
    'level_novice' => 'Novice',
    'level_intermediate' => 'Intermediate',
    'level_advanced' => 'Advanced',
    'level_expert' => 'Expert',
    'references' => 'References',
    'job_title' => 'Job Title',
    'company' => 'Company',
    'location' => 'Location',
    'years' => 'Years',
    'project_title' => 'Project Title',
    'project_year' => 'Year',
    'description' => 'Description',
    'degree_certificate' => 'Degree/Certificate',
    'institution' => 'Institution',
    'cgpa' => 'CGPA / GPA',
    'education_description' => 'Description / Final Year Project',
    'reference_full_name' => 'Full Name',
    'reference_relation_title' => 'Relation/Title',
    'reference_contact' => 'Contact (Email/Phone)',
    'add_button' => '+ Add',
    'remove_button' => '×',
    'generate_button' => 'Generate Resume',
    'dual_language_label' => 'Generate Dual-Language Resume',
    'dual_language_helper' => 'Requires you to fill in fields for both languages.',
    
    'english_section' => 'English Input',
    'malay_section' => 'Bahasa Melayu Input',

    // Placeholders
    'placeholder_tagline' => 'e.g., Results-Oriented Software Engineer',
    'placeholder_objective' => 'e.g., Seeking a challenging role in system development...',
    'placeholder_job_grade' => 'e.g., Grade F29',
    'placeholder_school_name' => 'e.g., SMK Putrajaya Presint 8 (1)',
    'placeholder_graduation_year' => 'e.g., 2016',
    'placeholder_key_achievements' => 'e.g., 8As in SPM (including A+ in English and Modern Mathematics)',
    'placeholder_language_name' => 'e.g., English',
    'placeholder_language_proficiency' => 'e.g., Professional Working Proficiency or MUET Band 4',
    'placeholder_skill_name' => 'e.g., Laravel Framework',
    
    // PDF Headers
    'pdf_objective' => 'Career Objective',
    'pdf_work_experience' => 'Work Experience',
    'pdf_projects' => 'Projects',
    'pdf_education' => 'Education',
    'pdf_secondary_education' => 'Secondary Education',
    'pdf_skills' => 'Skills',
    'pdf_languages' => 'Languages',
    'pdf_references' => 'References',
    'pdf_summary' => 'Professional Summary'
];