<?php
$lang = [
    // Header & Footer
    'app_title' => 'ResumeForge',
    'nav_create_resume' => 'Bina Resume',
    'nav_preview_design' => 'Pratonton Reka Bentuk',
    'footer_copyright' => '&copy; ' . date('Y') . ' ResumeForge. Hak Cipta Terpelihara.',

    // Index Page
    'form_main_title' => 'Penjana Resume Automatik',
    'form_main_subtitle' => 'Isi butiran di bawah untuk menjana resume profesional anda.',
    'template_selection' => 'Templat Resume',
    'template_modern' => 'Dua Lajur Moden',
    'template_classic' => 'Satu Lajur Klasik',
    'options' => 'Pilihan',

    // Field Labels & Legends
    'personal_details' => 'Butiran Peribadi',
    'profile_photo' => 'Gambar Profil',
    'full_name' => 'Nama Penuh',
    'professional_tagline' => 'Tagline Profesional',
    'email' => 'E-mel',
    'add_email' => 'Tambah e-mel lain',
    'phone' => 'Telefon',
    'physical_address' => 'Alamat Kediaman',
    'github_profile' => 'Profil GitHub',
    'career_objective' => 'Objektif Kerjaya',
    'professional_summary' => 'Ringkasan Profesional',
    'employment_history' => 'Pengalaman Kerja',
    'job_type' => 'Jenis Pekerjaan',
    'job_type_full_time' => 'Sepenuh Masa',
    'job_type_part_time' => 'Separuh Masa',
    'job_type_contract' => 'Kontrak',
    'job_type_internship' => 'Latihan Industri',
    'job_type_freelance' => 'Bekerja Sendiri',
    'job_grade' => 'Gred Rasmi / Anotasi (Pilihan)',
    'projects' => 'Projek',
    'education' => 'Pendidikan Tinggi (Universiti / Kolej)',
    'secondary_education' => 'Pendidikan Menengah (SPM / O-Level)',
    'school_name' => 'Nama Sekolah',
    'graduation_year' => 'Tahun Graduasi',
    'key_achievements_grades' => 'Pencapaian & Gred Utama',
    'skills' => 'Kemahiran Teknikal & Profesional',
    'languages' => 'Bahasa',
    'language_name' => 'Bahasa',
    'language_proficiency' => 'Tahap Penguasaan / Skor Ujian',
    'skill_name' => 'Nama Kemahiran',
    'proficiency_level' => 'Tahap Penguasaan',
    'level_novice' => 'Baru',
    'level_intermediate' => 'Pertengahan',
    'level_advanced' => 'Maju',
    'level_expert' => 'Pakar',
    'references' => 'Rujukan',
    'job_title' => 'Jawatan',
    'company' => 'Syarikat',
    'location' => 'Lokasi',
    'years' => 'Tahun',
    'project_title' => 'Tajuk Projek',
    'project_year' => 'Tahun',
    'description' => 'Penerangan',
    'degree_certificate' => 'Ijazah/Sijil',
    'institution' => 'Institusi',
    'cgpa' => 'PNGK / GPA',
    'education_description' => 'Penerangan / Projek Tahun Akhir',
    'reference_full_name' => 'Nama Penuh',
    'reference_relation_title' => 'Hubungan/Jawatan',
    'reference_contact' => 'Hubungi (E-mel/Telefon)',
    'add_button' => '+ Tambah',
    'remove_button' => '×',
    'generate_button' => 'Jana Resume',
    'dual_language_label' => 'Jana Resume Dwi-Bahasa',
    'dual_language_helper' => 'Memerlukan anda mengisi medan untuk kedua-dua bahasa.',
    
    'english_section' => 'Input Bahasa Inggeris',
    'malay_section' => 'Input Bahasa Melayu',

    // Placeholders
    'placeholder_tagline' => 'cth., Graduan Kejuruteraan Perisian Berorientasikan Hasil',
    'placeholder_objective' => 'cth., Mencari peranan yang mencabar dalam pembangunan sistem...',
    'placeholder_job_grade' => 'cth., Gred F29',
    'placeholder_school_name' => 'cth., SMK Putrajaya Presint 8 (1)',
    'placeholder_graduation_year' => 'cth., 2016',
    'placeholder_key_achievements' => 'cth., 8A dalam SPM (termasuk A+ untuk Bahasa Inggeris dan Matematik Moden)',
    'placeholder_language_name' => 'cth., Bahasa Melayu',
    'placeholder_language_proficiency' => 'cth., Cekap atau MUET Band 4',
    'placeholder_skill_name' => 'cth., Kerangka Kerja Laravel',

    // PDF Headers
    'pdf_objective' => 'Objektif Kerjaya',
    'pdf_work_experience' => 'Pengalaman Kerja',
    'pdf_projects' => 'Projek',
    'pdf_education' => 'Pendidikan',
    'pdf_secondary_education' => 'Pendidikan Menengah',
    'pdf_skills' => 'Kemahiran',
    'pdf_languages' => 'Bahasa',
    'pdf_references' => 'Rujukan',
    'pdf_summary' => 'Ringkasan Profesional'
];