<?php
$lang = [
    // Header & Footer
    'app_title' => 'ResumeForge',
    'nav_create_resume' => 'Create Resume',
    'nav_preview_design' => 'Preview Design',
    'footer_copyright' => '&copy; ' . date('Y') . ' ResumeForge. All Rights Reserved.',

    // Index Page
    'form_main_title' => 'Auto Resume Creator',
    'form_main_subtitle' => 'Fill in the details below to generate your professional resume.',
    'options' => 'Options',
    'template_selection' => 'Resume Template',
    'template_modern' => 'Modern Two-Column',
    'template_classic' => 'Classic Single-Column',

    // Field Labels & Legends
    'personal_details' => 'Personal Details',
    'profile_photo' => 'Profile Photo',
    'full_name' => 'Full Name',
    'professional_tagline' => 'Professional Tagline',
    'email' => 'Email',
    'add_email' => 'Add another email',
    'phone' => 'Phone',
    'physical_address' => 'Physical Address',
    'github_profile' => 'GitHub Profile',
    'career_objective' => 'Career Objective',
    'professional_summary' => 'Professional Summary',
    'employment_history' => 'Work Experience',
    'job_type' => 'Job Type',
    'job_type_full_time' => 'Full-time',
    'job_type_part_time' => 'Part-time',
    'job_type_contract' => 'Contract',
    'job_type_internship' => 'Internship',
    'job_type_freelance' => 'Freelance',
    'job_grade' => 'Official Grade / Annotation (Optional)',
    'projects' => 'Projects',
    'education' => 'Tertiary Education (University / College)',
    'secondary_education' => 'Secondary Education (SPM / O-Level)',
    'school_name' => 'School Name',
    'graduation_year' => 'Graduation Year',
    'key_achievements_grades' => 'Key Achievements & Grades',
    'skills' => 'Technical & Professional Skills',
    'languages' => 'Languages',
    'language_name' => 'Language',
    'language_proficiency' => 'Proficiency / Test Score',
    'skill_name' => 'Skill Name',
    'proficiency_level' => 'Proficiency Level',
    'level_novice' => 'Novice',
    'level_intermediate' => 'Intermediate',
    'level_advanced' => 'Advanced',
    'level_expert' => 'Expert',
    'references' => 'References',
    'job_title' => 'Job Title',
    'company' => 'Company',
    'location' => 'Location',
    'years' => 'Years',
    'project_title' => 'Project Title',
    'project_year' => 'Year',
    'description' => 'Description',
    'degree_certificate' => 'Degree/Certificate',
    'institution' => 'Institution',
    'cgpa' => 'CGPA / GPA',
    'education_description' => 'Description / Final Year Project',
    'reference_full_name' => 'Full Name',
    'reference_relation_title' => 'Relation/Title',
    'reference_contact' => 'Contact (Email/Phone)',
    'add_button' => '+ Add',
    'remove_button' => '×',
    'generate_button' => 'Generate Resume',
    'dual_language_label' => 'Generate Dual-Language Resume',
    'dual_language_helper' => 'Requires you to fill in fields for both languages.',
    
    'english_section' => 'English',
    'malay_section' => 'Bahasa Melayu',

    // Placeholders
    'placeholder_full_name' => 'e.g., John Doe',
    'placeholder_tagline' => 'e.g., Results-Oriented Software Engineer',
    'placeholder_email' => 'e.g., john.doe@example.com',
    'placeholder_phone' => 'e.g., 123-456-7890',
    'placeholder_address' => 'e.g., 123 Main St, 50000 Kuala Lumpur',
    'placeholder_github' => 'e.g., https://github.com/johndoe',
    'placeholder_objective' => 'e.g., Seeking a challenging role in system development...',
    'placeholder_summary' => 'e.g., A highly motivated software engineer with...',
    'placeholder_job_title' => 'e.g., Senior Web Developer',
    'placeholder_company' => 'e.g., Tech Solutions Inc.',
    'placeholder_job_grade' => 'e.g., Grade F29',
    'placeholder_location' => 'e.g., Kuala Lumpur, Malaysia',
    'placeholder_years' => 'e.g., 2020 - Present',
    'placeholder_description' => 'e.g., Led development of key projects...',
    'placeholder_project_title' => 'e.g., Smart Waste Management System',
    'placeholder_project_year' => 'e.g., 2023',
    'placeholder_degree' => 'e.g., B.S. in Computer Science',
    'placeholder_institution' => 'e.g., University of Technology',
    'placeholder_cgpa' => 'e.g., 3.75 / 4.00',
    'placeholder_education_description' => 'e.g., Final Year Project: AI Chatbot...',
    'placeholder_education_years' => 'e.g., 2020 - 2024',
    'placeholder_school_name' => 'e.g., SMK Putrajaya Presint 8 (1)',
    'placeholder_graduation_year' => 'e.g., 2016',
    'placeholder_key_achievements' => 'e.g., 8As in SPM...',
    'placeholder_language_name' => 'e.g., English',
    'placeholder_language_proficiency' => 'e.g., Native or MUET Band 4',
    'placeholder_skill_name' => 'e.g., Laravel Framework',
    'placeholder_ref_name' => 'e.g., Dr. Jane Smith',
    'placeholder_ref_relation' => 'e.g., Former Manager, Tech Solutions Inc.',
    'placeholder_ref_contact' => 'e.g., jane.smith@example.com',

    // PDF Headers
    'pdf_objective' => 'Career Objective',
    'pdf_work_experience' => 'Work Experience',
    'pdf_projects' => 'Projects',
    'pdf_education' => 'Education',
    'pdf_secondary_education' => 'Secondary Education',
    'pdf_skills' => 'Skills',
    'pdf_languages' => 'Languages',
    'pdf_references' => 'References',
    'pdf_summary' => 'Professional Summary'
];